name: KellyGroup Automation
on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, ready_for_review]

jobs:
  sync-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      actions: write

    steps:
      - name: Add to Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/patgpt/projects/12
          github-token: ${{ secrets.PROJECT_TOKEN }}
          labeled: "priority:high,cms-update"
          label-operator: OR

      - name: Move Labeled Items
        uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: ${{ secrets.PROJECT_TOKEN }}
          project-url: https://github.com/users/patgpt/projects/12
          column-name: "In Progress"
          label-name: "priority:high"
