name: KellyGroup Production Workflow
on:
  issues:
    types: [opened, labeled, closed]
  pull_request:
    types: [opened, ready_for_review, closed]
  push:
    branches: [main]
    paths:
      - "contentful/**"
      - "drizzle/migrations/**"

env:
  PROJECT_URL: https://github.com/users/patgpt/projects/12
  CONTENTFUL_ENV: master

jobs:
  project-board:
    name: Project Automation
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      issues: write
      pull-requests: write
      contents: read
      actions: write

    steps:
      - name: Add to Project Board
        uses: actions/add-to-project@v1
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_TOKEN }}

      - name: Sync Custom Fields
        uses: konradpabjan/action-project-board@v3.1
        with:
          owner: "@me"
          project-number: 12
          field-mapping: |
            "Client_Priority" → "${{ github.event.issue.labels.*.name }}"
            "Implementation_Status" → |
              case:
                contains(github.event.issue.labels.*.name, 'priority:urgent') → "In_Development"
                contains(github.event.issue.labels.*.name, 'ready-for-review') → "Code_Review"
                default → "Not_Started"
          github-token: ${{ secrets.PROJECT_TOKEN }}

      - name: Move Urgent Items
        uses: srggrs/automove-project-items@v1
        with:
          project-url: ${{ env.PROJECT_URL }}
          from-column: "To Do"
          to-column: "In Progress"
          when-label: "priority:urgent"
          github-token: ${{ secrets.PROJECT_TOKEN }}

  contentful-sync:
    name: CMS Updates
    runs-on: ubuntu-latest
    needs: project-board
    steps:
      - name: Handle Contentful Changes
        uses: contentful/github-action@v1
        with:
          space-id: ${{ vars.CONTENTFUL_SPACE_ID }}
          access-token: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          environment-id: ${{ env.CONTENTFUL_ENV }}
          trigger-label: "cms-update"
          github-token: ${{ secrets.PROJECT_TOKEN }}

  db-migrations:
    name: Database Schema
    runs-on: ubuntu-latest
    steps:
      - name: Track Migrations
        if: contains(github.event.head_commit.message, 'migration:')
        run: |
          gh issue create \
            --title "DB Migration Detected [${{ github.sha }}]" \
            --body "**Commit:** ${{ github.sha }}\n**Message:** ${{ github.event.head_commit.message }}" \
            --label "db-migration,priority:high"
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
